# Blocco proxy condiviso verso CKAN (riusato sia in HTTP sia in HTTPS)
# tramite include. Vedi i due server block sotto.

server {
    # ---- Accesso NON-SSL ----
    listen       80;
    listen  [::]:80;
    server_name  _;

    location / {
        proxy_pass http://ckan:5000/;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $cookie_auth_tkt;
        proxy_no_cache $cookie_auth_tkt;
        proxy_cache_valid 30m;
        proxy_cache_key $host$scheme$proxy_host$request_uri;
    }
}

server {
    # ---- Accesso SSL (certificato self-signed in demo) ----
    listen       443 ssl;
    listen  [::]:443 ssl;
    server_name  _;

    ssl_certificate     /etc/nginx/certs/ckan-local.crt;
    ssl_certificate_key /etc/nginx/certs/ckan-local.key;

    # TLS 1.2 & 1.3 only
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    location / {
        proxy_pass http://ckan:5000/;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $cookie_auth_tkt;
        proxy_no_cache $cookie_auth_tkt;
        proxy_cache_valid 30m;
        proxy_cache_key $host$scheme$proxy_host$request_uri;
    }
}
